### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by till** [passionsplay/wp-asciinema#1]
I made some changes locally. Was wondering if you'd like a PR. Also, can you add a license to your code?

Cheers!

**Comment by opicron** [comment]
I'd like to know too, as I just added an issue. If not I will fork and maintain my own version.

**Comment by bgturner** [comment]
Hey! You're right that this hasn't been maintained!

I'm getting back into blogging and hope to update this code soon. If I'm honest, it probably won't happen soon, but maybe! 

I don't have a roadmap yet, but the two main things I'd like to do:

- Make this plugin integrate better with WP's media library
- Create a Gutenberg Block instead of a shortcode

> can you add a license to your code?

Done! Thanks for the nudge! https://github.com/passionsplay/wp-asciinema/pull/3

I'll close this issue since I've clarified if this issue is maintained -- it sort of is? :D
